### ISSUE TITLE
Just a question :-)

### ISSUE THREAD

**Issue by ppmac** [Jorl17/jar2app#1]
This is not really an issue.

You know that Gentoo is considered by many to be the most powerful distribution of GNU/Linux. In Gentoo, you compile every program from source, rather than using the distribution maintainers' precompiled binaries. This means that every program is specially tailored to your system and needs and is better optimized. 

Why did you switch from Gentoo GNU/Linux to Mac OS ? What made you change your mind?

**Comment by Jorl17** [comment]
My laptop went haywire in a critical stage of my semester. Wouldn't charge, estimated fixes were months and I was particularly fed up with many things about it. I had been seduced by Mac OS X machines, and even several talks about how its "butchered Microkernel" works, and decided I'd replace it with a Mac instead of another machine. I ran Linux for about 8 years or so.

I was looking for hardware that I knew would work great and reliably. While I know there's other hardware out there that can do this, I wasn't willing to put the effort into researching it, so I went with the safe hardware that I knew would work (and to be honest it hasn't failed me).

Furthermore, I had become tired of messing with endless config files or adjusting every little detail of every application to get the system to really cooperate with me. If I wanted to run Skype, I'd run into some troubles with libraries for ALSA and pulseaudio mismatching 32bits vs 64 bits, for example. I also really liked the way that the trackpad on Mac machines work, and that hasn't changed -- it's now a great part of my workflow.

So, in a way, you can say that I was just tired of configuring things over and over to get out of my way. Mac OS X is mostly out of my way. There are somethings I'd do differently, but it usually cooperates and I'm quite happy with it.

With that said, I was not expecting such a command line friendly system when I came to Mac OS X. I don't know how you know I came from Gentoo (I have some guesses), but that's the last Linux flavor I ran full time. The brew (and brew cask) package managers are amazing and have always given me feature parity with Linux. Everything that I did use in Linux I also use in Mac OS X. Even configuring Wine, as counterintuitive as it may seem, is made easier with Wineskin. Every situation where I turned to the command line in Linux, I turn to the command line in OSX...with the exception of things for which there is indeed an easier to use interface.

I remember that I was also getting frustrated with the time it took for Gentoo to build most packages, and the whole NVIDIA Bumblebee debacle (my laptop was one of them) which essentially meant it was a miracle for me to get graphics to work decently. I once upgraded the system and spent the whole day just getting X to run again. The "every program is specially tailored to your system and needs and is better optimized." was my mantra too, until it become quite obvious to me that Gentoo didn't really give me any performance boost in particular (compared to other distros I perviously ran), but it just made everything take longer to work around, and more cumbersome. Of course I can and should also attribute this to my novice using Gentoo, and, well, I do.

So Mac OS X gives me a great development environment, and desktop environment too. I don't miss nearly anything from Linux, with the exception of a certain spirit of reward for running mostly FLOSS software. I understand this might not be the case for everyone else, but then again I don't go around saying "stop running GNU/Linux and start running Mac OS X", not by a chance. It works for me, does what I want the way I want it to. Applications mostly just work as intended, and I don't have fiddle with them or with the system to get it to work. I do complain about somethings that I find ridiculous or poorly developed...I did that when I ran GNU/Linux too.

Nevertheless, I still use Linux for many things and in many scenarios. My primary machine is OS X, that's all. You'll notice that most of the (small) software I write is intentionally compatible with OS X and Linux. I don't find Linux inferior at all, I just think I don't want to invest so much time into getting everything perfect. Mac OS X isn't perfect, by by default, for me, it's much closer to that.

So, in real hindsight, I'd probably also be happy with GNU/Linux and a new machine. But I was seduced by a Mac, I had the chance, and I'm not disappointed at all. Plus, Time Machine is amazing -- I know there might be equivalents in Linux, but, again, Time machine took me one minute to configure, and that was it.

P.S: You can reply to my email if you want. I think it's public :)

**Comment by ppmac** [comment]
Thanks for the answer ;)
I was just curious why would some "Gentoo wizard" switch to Mac.
You might be wondering how i know you used Gentoo. I'm from your department (DEI).

Cheers.

**Comment by Jorl17** [comment]
Well, glad I could "help". 

I'm no Gentoo wizard, though! But thanks for the compliment!
