### ISSUE TITLE
Use splash screen

### ISSUE THREAD

**Issue by matthijs110** [Jorl17/jar2app#12]
Is it possible to load a splash screen as well?

**Comment by Jorl17** [comment]
(TLDR; No)

Hi.

`jar2app` packages the `jar` and a simple executable from `AppBundler` which itself launches the JAR. It is therefore not easy to load a splash screen. You can look into this yourself by producing an alternative to appbundler or by adding an intermediary executable which executes instead of AppBundler and then invokes it. 

However, I would recommend adding any splashscreen logic inside the JAR itself. If such is not possible (e.g. no source-code access), perhaps creating a new JAR which opens the "real one" and adds the splashscreen might be worth considering.

If it's something much more sophisticated, then indeed the way to go is to use an alternative to AppBundler, in which case you might want to pass on `jar2app` altogether because you'll be using something like XCode which can already package the contents for you.

**Comment by Jorl17** [comment]
Closing issues without any clear relationship with jar2app
