### ISSUE TITLE
Use macOS menu bar

### ISSUE THREAD

**Issue by fluidblue** [Jorl17/jar2app#8]
Hello,

I like to have the macOS menu bar to be used instead of the Java menu bars.
For example, the menu bar of [Umlet](http://www.umlet.com/) shown as a native macOS menu bar.

I used to do this with XCode's Jar Bundler, using [the option "Use Macintosh menu Bar"](http://alvinalexander.com/apple/mac/java-jar-bundler/Getting_started_with_Jar_Bu.shtml#SECTION00420000000000000000). This worked fine, but Jar Bundler is now discontinued.

There seems also a [command line flag](http://stackoverflow.com/a/8956715/2013757) for achieving it.

Regards,
Max

**Comment by Jorl17** [comment]
Hi!

I will add support for this feature in the coming days. It will be added as a simple command line flag.

Thanks for your report!

**Comment by Jorl17** [comment]
I've pushed to master an attempt at fixing this (https://github.com/Jorl17/jar2app/commit/21c6b71dbe8a6400697fd0ae3a07021b12780dd3). However, this is very application dependent and it should be done at the application/jar level instead of .app level. There's not too much we can control.

The fix adds an optional `-o` option which you can pass (e.g. `jar2app -o myapp`) to use the macOS menubar.

Please tell me if you have managed to achieve your goals with this flag. Thanks!

**Comment by fluidblue** [comment]
Unfortunately, it doesn't work with Umlet. I tried `jar2app "umlet-standalone-14.2/umlet.jar" --use-osx-menubar` and copied all other files of Umlet into the .app file. The resulting app works fine, but the macOS menu bar is not used (using macOS 10.12.2).

As you said, it may be application dependent, so I posted an [issue](https://github.com/umlet/umlet/issues/419) in the Umlet issue tracker.

**Comment by fluidblue** [comment]
No problem. Thanks for looking into it!

**Comment by Jorl17** [comment]
Closing this issue as it seems that the app does the most it can right now.
